version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 30
  complex-logic:
    enabled: true
    config:
      threshold: 30
  file-lines:
    enabled: true
    config:
      threshold: 1000
  method-complexity:
    enabled: true
    config:
      threshold: 25
  method-count:
    enabled: true
    config:
      threshold: 50
  method-lines:
    enabled: true
    config:
      threshold: 400
  nested-control-flow:
    enabled: true
    config:
      threshold: 10
  return-statements:
    enabled: true
    config:
      threshold: 10
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
plugins:
 rubocop:
  enabled: true
 eslint:
  enabled: true
exclude_patterns:

- "models/"
- "features/"
- "server/node_modules/"
- "script/"
- "**/test/"

